[package]
name="aspiesolutions-lib-rust"
version="0.1.0"
edition="2021"
[lib]
crate_type=["cdylib","staticlib","rlib"]

[dependencies]
log = "0.4.17"
libc = "0.2.135"
thiserror = "1.0.37"
# tokio = "1.21.2"
# serde = "1.0.145"